/**
 * @file seoKeywords.js
 * @description Centralized SEO Keyword Database & Structured Data Generator.
 * Maps top high-intent keywords (from the 500 master keyword target list) to
 * pages, sub-pages, and individual PDF tools. Generates Schema.org JSON-LD definitions.
 */

export const MASTER_SEO_KEYWORDS = [
  "PDF",
  "PDF Viewer",
  "PDF Reader",
  "PDF Editor",
  "PDF Converter",
  "PDF Compressor",
  "PDF Merger",
  "PDF Splitter",
  "PDF Creator",
  "PDF Generator",
  "Online PDF",
  "Free PDF",
  "Secure PDF",
  "PDF Download",
  "PDF Upload",
  "PDF Processing",
  "PDF Management",
  "PDF OCR",
  "PDF Scanner",
  "PDF Signer",
  "Online View Pdf",
  "Online View Pdf File",
  "Online View Pdf Document",
  "Online View Document Pdf",
  "Online View Digital Pdf",
  "Online Read Pdf",
  "Online Read Pdf File",
  "Online Read Pdf Document",
  "Online Read Document Pdf",
  "Online Read Digital Pdf",
  "Online Edit Pdf",
  "Online Edit Pdf File",
  "Online Edit Pdf Document",
  "Online Edit Document Pdf",
  "Online Edit Digital Pdf",
  "Online Convert Pdf",
  "Online Convert Pdf File",
  "Online Convert Pdf Document",
  "Online Convert Document Pdf",
  "Online Convert Digital Pdf",
  "Online Compress Pdf",
  "Online Compress Pdf File",
  "Online Compress Pdf Document",
  "Online Compress Document Pdf",
  "Online Compress Digital Pdf",
  "Online Merge Pdf",
  "Online Merge Pdf File",
  "Online Merge Pdf Document",
  "Online Merge Document Pdf",
  "Online Merge Digital Pdf",
  "Online Split Pdf",
  "Online Split Pdf File",
  "Online Split Pdf Document",
  "Online Split Document Pdf",
  "Online Split Digital Pdf",
  "Online Protect Pdf",
  "Online Protect Pdf File",
  "Online Protect Pdf Document",
  "Online Protect Document Pdf",
  "Online Protect Digital Pdf",
  "Online Unlock Pdf",
  "Online Unlock Pdf File",
  "Online Unlock Pdf Document",
  "Online Unlock Document Pdf",
  "Online Unlock Digital Pdf",
  "Online Rotate Pdf",
  "Online Rotate Pdf File",
  "Online Rotate Pdf Document",
  "Online Rotate Document Pdf",
  "Online Rotate Digital Pdf",
  "Online Organize Pdf",
  "Online Organize Pdf File",
  "Online Organize Pdf Document",
  "Online Organize Document Pdf",
  "Online Organize Digital Pdf",
  "Online Extract Pdf",
  "Online Extract Pdf File",
  "Online Extract Pdf Document",
  "Online Extract Document Pdf",
  "Online Extract Digital Pdf",
  "Online Annotate Pdf",
  "Online Annotate Pdf File",
  "Online Annotate Pdf Document",
  "Online Annotate Document Pdf",
  "Online Annotate Digital Pdf",
  "Online Sign Pdf",
  "Online Sign Pdf File",
  "Online Sign Pdf Document",
  "Online Sign Document Pdf",
  "Online Sign Digital Pdf",
  "Online Print Pdf",
  "Online Print Pdf File",
  "Online Print Pdf Document",
  "Online Print Document Pdf",
  "Online Print Digital Pdf",
  "Online Share Pdf",
  "Online Share Pdf File",
  "Online Share Pdf Document",
  "Online Share Document Pdf",
  "Online Share Digital Pdf",
  "Online Search Pdf",
  "Online Search Pdf File",
  "Online Search Pdf Document",
  "Online Search Document Pdf",
  "Online Search Digital Pdf",
  "Online Optimize Pdf",
  "Online Optimize Pdf File",
  "Online Optimize Pdf Document",
  "Online Optimize Document Pdf",
  "Online Optimize Digital Pdf",
  "Online Repair Pdf",
  "Online Repair Pdf File",
  "Online Repair Pdf Document",
  "Online Repair Document Pdf",
  "Online Repair Digital Pdf",
  "Online Redact Pdf",
  "Online Redact Pdf File",
  "Online Redact Pdf Document",
  "Online Redact Document Pdf",
  "Online Redact Digital Pdf",
  "Free View Pdf",
  "Free View Pdf File",
  "Free View Pdf Document",
  "Free View Document Pdf",
  "Free View Digital Pdf",
  "Free Read Pdf",
  "Free Read Pdf File",
  "Free Read Pdf Document",
  "Free Read Document Pdf",
  "Free Read Digital Pdf",
  "Free Edit Pdf",
  "Free Edit Pdf File",
  "Free Edit Pdf Document",
  "Free Edit Document Pdf",
  "Free Edit Digital Pdf",
  "Free Convert Pdf",
  "Free Convert Pdf File",
  "Free Convert Pdf Document",
  "Free Convert Document Pdf",
  "Free Convert Digital Pdf",
  "Free Compress Pdf",
  "Free Compress Pdf File",
  "Free Compress Pdf Document",
  "Free Compress Document Pdf",
  "Free Compress Digital Pdf",
  "Free Merge Pdf",
  "Free Merge Pdf File",
  "Free Merge Pdf Document",
  "Free Merge Document Pdf",
  "Free Merge Digital Pdf",
  "Free Split Pdf",
  "Free Split Pdf File",
  "Free Split Pdf Document",
  "Free Split Document Pdf",
  "Free Split Digital Pdf",
  "Free Protect Pdf",
  "Free Protect Pdf File",
  "Free Protect Pdf Document",
  "Free Protect Document Pdf",
  "Free Protect Digital Pdf",
  "Free Unlock Pdf",
  "Free Unlock Pdf File",
  "Free Unlock Pdf Document",
  "Free Unlock Document Pdf",
  "Free Unlock Digital Pdf",
  "Free Rotate Pdf",
  "Free Rotate Pdf File",
  "Free Rotate Pdf Document",
  "Free Rotate Document Pdf",
  "Free Rotate Digital Pdf",
  "Free Organize Pdf",
  "Free Organize Pdf File",
  "Free Organize Pdf Document",
  "Free Organize Document Pdf",
  "Free Organize Digital Pdf",
  "Free Extract Pdf",
  "Free Extract Pdf File",
  "Free Extract Pdf Document",
  "Free Extract Document Pdf",
  "Free Extract Digital Pdf",
  "Free Annotate Pdf",
  "Free Annotate Pdf File",
  "Free Annotate Pdf Document",
  "Free Annotate Document Pdf",
  "Free Annotate Digital Pdf",
  "Free Sign Pdf",
  "Free Sign Pdf File",
  "Free Sign Pdf Document",
  "Free Sign Document Pdf",
  "Free Sign Digital Pdf",
  "Free Print Pdf",
  "Free Print Pdf File",
  "Free Print Pdf Document",
  "Free Print Document Pdf",
  "Free Print Digital Pdf",
  "Free Share Pdf",
  "Free Share Pdf File",
  "Free Share Pdf Document",
  "Free Share Document Pdf",
  "Free Share Digital Pdf",
  "Free Search Pdf",
  "Free Search Pdf File",
  "Free Search Pdf Document",
  "Free Search Document Pdf",
  "Free Search Digital Pdf",
  "Free Optimize Pdf",
  "Free Optimize Pdf File",
  "Free Optimize Pdf Document",
  "Free Optimize Document Pdf",
  "Free Optimize Digital Pdf",
  "Free Repair Pdf",
  "Free Repair Pdf File",
  "Free Repair Pdf Document",
  "Free Repair Document Pdf",
  "Free Repair Digital Pdf",
  "Free Redact Pdf",
  "Free Redact Pdf File",
  "Free Redact Pdf Document",
  "Free Redact Document Pdf",
  "Free Redact Digital Pdf",
  "Best View Pdf",
  "Best View Pdf File",
  "Best View Pdf Document",
  "Best View Document Pdf",
  "Best View Digital Pdf",
  "Best Read Pdf",
  "Best Read Pdf File",
  "Best Read Pdf Document",
  "Best Read Document Pdf",
  "Best Read Digital Pdf",
  "Best Edit Pdf",
  "Best Edit Pdf File",
  "Best Edit Pdf Document",
  "Best Edit Document Pdf",
  "Best Edit Digital Pdf",
  "Best Convert Pdf",
  "Best Convert Pdf File",
  "Best Convert Pdf Document",
  "Best Convert Document Pdf",
  "Best Convert Digital Pdf",
  "Best Compress Pdf",
  "Best Compress Pdf File",
  "Best Compress Pdf Document",
  "Best Compress Document Pdf",
  "Best Compress Digital Pdf",
  "Best Merge Pdf",
  "Best Merge Pdf File",
  "Best Merge Pdf Document",
  "Best Merge Document Pdf",
  "Best Merge Digital Pdf",
  "Best Split Pdf",
  "Best Split Pdf File",
  "Best Split Pdf Document",
  "Best Split Document Pdf",
  "Best Split Digital Pdf",
  "Best Protect Pdf",
  "Best Protect Pdf File",
  "Best Protect Pdf Document",
  "Best Protect Document Pdf",
  "Best Protect Digital Pdf",
  "Best Unlock Pdf",
  "Best Unlock Pdf File",
  "Best Unlock Pdf Document",
  "Best Unlock Document Pdf",
  "Best Unlock Digital Pdf",
  "Best Rotate Pdf",
  "Best Rotate Pdf File",
  "Best Rotate Pdf Document",
  "Best Rotate Document Pdf",
  "Best Rotate Digital Pdf",
  "Best Organize Pdf",
  "Best Organize Pdf File",
  "Best Organize Pdf Document",
  "Best Organize Document Pdf",
  "Best Organize Digital Pdf",
  "Best Extract Pdf",
  "Best Extract Pdf File",
  "Best Extract Pdf Document",
  "Best Extract Document Pdf",
  "Best Extract Digital Pdf",
  "Best Annotate Pdf",
  "Best Annotate Pdf File",
  "Best Annotate Pdf Document",
  "Best Annotate Document Pdf",
  "Best Annotate Digital Pdf",
  "Best Sign Pdf",
  "Best Sign Pdf File",
  "Best Sign Pdf Document",
  "Best Sign Document Pdf",
  "Best Sign Digital Pdf",
  "Best Print Pdf",
  "Best Print Pdf File",
  "Best Print Pdf Document",
  "Best Print Document Pdf",
  "Best Print Digital Pdf",
  "Best Share Pdf",
  "Best Share Pdf File",
  "Best Share Pdf Document",
  "Best Share Document Pdf",
  "Best Share Digital Pdf",
  "Best Search Pdf",
  "Best Search Pdf File",
  "Best Search Pdf Document",
  "Best Search Document Pdf",
  "Best Search Digital Pdf",
  "Best Optimize Pdf",
  "Best Optimize Pdf File",
  "Best Optimize Pdf Document",
  "Best Optimize Document Pdf",
  "Best Optimize Digital Pdf",
  "Best Repair Pdf",
  "Best Repair Pdf File",
  "Best Repair Pdf Document",
  "Best Repair Document Pdf",
  "Best Repair Digital Pdf",
  "Best Redact Pdf",
  "Best Redact Pdf File",
  "Best Redact Pdf Document",
  "Best Redact Document Pdf",
  "Best Redact Digital Pdf",
  "Fast View Pdf",
  "Fast View Pdf File",
  "Fast View Pdf Document",
  "Fast View Document Pdf",
  "Fast View Digital Pdf",
  "Fast Read Pdf",
  "Fast Read Pdf File",
  "Fast Read Pdf Document",
  "Fast Read Document Pdf",
  "Fast Read Digital Pdf",
  "Fast Edit Pdf",
  "Fast Edit Pdf File",
  "Fast Edit Pdf Document",
  "Fast Edit Document Pdf",
  "Fast Edit Digital Pdf",
  "Fast Convert Pdf",
  "Fast Convert Pdf File",
  "Fast Convert Pdf Document",
  "Fast Convert Document Pdf",
  "Fast Convert Digital Pdf",
  "Fast Compress Pdf",
  "Fast Compress Pdf File",
  "Fast Compress Pdf Document",
  "Fast Compress Document Pdf",
  "Fast Compress Digital Pdf",
  "Fast Merge Pdf",
  "Fast Merge Pdf File",
  "Fast Merge Pdf Document",
  "Fast Merge Document Pdf",
  "Fast Merge Digital Pdf",
  "Fast Split Pdf",
  "Fast Split Pdf File",
  "Fast Split Pdf Document",
  "Fast Split Document Pdf",
  "Fast Split Digital Pdf",
  "Fast Protect Pdf",
  "Fast Protect Pdf File",
  "Fast Protect Pdf Document",
  "Fast Protect Document Pdf",
  "Fast Protect Digital Pdf",
  "Fast Unlock Pdf",
  "Fast Unlock Pdf File",
  "Fast Unlock Pdf Document",
  "Fast Unlock Document Pdf",
  "Fast Unlock Digital Pdf",
  "Fast Rotate Pdf",
  "Fast Rotate Pdf File",
  "Fast Rotate Pdf Document",
  "Fast Rotate Document Pdf",
  "Fast Rotate Digital Pdf",
  "Fast Organize Pdf",
  "Fast Organize Pdf File",
  "Fast Organize Pdf Document",
  "Fast Organize Document Pdf",
  "Fast Organize Digital Pdf",
  "Fast Extract Pdf",
  "Fast Extract Pdf File",
  "Fast Extract Pdf Document",
  "Fast Extract Document Pdf",
  "Fast Extract Digital Pdf",
  "Fast Annotate Pdf",
  "Fast Annotate Pdf File",
  "Fast Annotate Pdf Document",
  "Fast Annotate Document Pdf",
  "Fast Annotate Digital Pdf",
  "Fast Sign Pdf",
  "Fast Sign Pdf File",
  "Fast Sign Pdf Document",
  "Fast Sign Document Pdf",
  "Fast Sign Digital Pdf",
  "Fast Print Pdf",
  "Fast Print Pdf File",
  "Fast Print Pdf Document",
  "Fast Print Document Pdf",
  "Fast Print Digital Pdf",
  "Fast Share Pdf",
  "Fast Share Pdf File",
  "Fast Share Pdf Document",
  "Fast Share Document Pdf",
  "Fast Share Digital Pdf",
  "Fast Search Pdf",
  "Fast Search Pdf File",
  "Fast Search Pdf Document",
  "Fast Search Document Pdf",
  "Fast Search Digital Pdf",
  "Fast Optimize Pdf",
  "Fast Optimize Pdf File",
  "Fast Optimize Pdf Document",
  "Fast Optimize Document Pdf",
  "Fast Optimize Digital Pdf",
  "Fast Repair Pdf",
  "Fast Repair Pdf File",
  "Fast Repair Pdf Document",
  "Fast Repair Document Pdf",
  "Fast Repair Digital Pdf",
  "Fast Redact Pdf",
  "Fast Redact Pdf File",
  "Fast Redact Pdf Document",
  "Fast Redact Document Pdf",
  "Fast Redact Digital Pdf",
  "Secure View Pdf",
  "Secure View Pdf File",
  "Secure View Pdf Document",
  "Secure View Document Pdf",
  "Secure View Digital Pdf",
  "Secure Read Pdf",
  "Secure Read Pdf File",
  "Secure Read Pdf Document",
  "Secure Read Document Pdf",
  "Secure Read Digital Pdf",
  "Secure Edit Pdf",
  "Secure Edit Pdf File",
  "Secure Edit Pdf Document",
  "Secure Edit Document Pdf",
  "Secure Edit Digital Pdf",
  "Secure Convert Pdf",
  "Secure Convert Pdf File",
  "Secure Convert Pdf Document",
  "Secure Convert Document Pdf",
  "Secure Convert Digital Pdf",
  "Secure Compress Pdf",
  "Secure Compress Pdf File",
  "Secure Compress Pdf Document",
  "Secure Compress Document Pdf",
  "Secure Compress Digital Pdf",
  "Secure Merge Pdf",
  "Secure Merge Pdf File",
  "Secure Merge Pdf Document",
  "Secure Merge Document Pdf",
  "Secure Merge Digital Pdf",
  "Secure Split Pdf",
  "Secure Split Pdf File",
  "Secure Split Pdf Document",
  "Secure Split Document Pdf",
  "Secure Split Digital Pdf",
  "Secure Protect Pdf",
  "Secure Protect Pdf File",
  "Secure Protect Pdf Document",
  "Secure Protect Document Pdf",
  "Secure Protect Digital Pdf",
  "Secure Unlock Pdf",
  "Secure Unlock Pdf File",
  "Secure Unlock Pdf Document",
  "Secure Unlock Document Pdf",
  "Secure Unlock Digital Pdf",
  "Secure Rotate Pdf",
  "Secure Rotate Pdf File",
  "Secure Rotate Pdf Document",
  "Secure Rotate Document Pdf",
  "Secure Rotate Digital Pdf",
  "Secure Organize Pdf",
  "Secure Organize Pdf File",
  "Secure Organize Pdf Document",
  "Secure Organize Document Pdf",
  "Secure Organize Digital Pdf",
  "Secure Extract Pdf",
  "Secure Extract Pdf File",
  "Secure Extract Pdf Document",
  "Secure Extract Document Pdf",
  "Secure Extract Digital Pdf",
  "Secure Annotate Pdf",
  "Secure Annotate Pdf File",
  "Secure Annotate Pdf Document",
  "Secure Annotate Document Pdf",
  "Secure Annotate Digital Pdf",
  "Secure Sign Pdf",
  "Secure Sign Pdf File",
  "Secure Sign Pdf Document",
  "Secure Sign Document Pdf",
  "Secure Sign Digital Pdf",
  "Secure Print Pdf",
  "Secure Print Pdf File",
  "Secure Print Pdf Document",
  "Secure Print Document Pdf",
  "Secure Print Digital Pdf",
  "Secure Share Pdf",
  "Secure Share Pdf File",
  "Secure Share Pdf Document",
  "Secure Share Document Pdf",
  "Secure Share Digital Pdf",
  "Secure Search Pdf",
  "Secure Search Pdf File",
  "Secure Search Pdf Document",
  "Secure Search Document Pdf",
  "Secure Search Digital Pdf",
  "Secure Optimize Pdf",
  "Secure Optimize Pdf File",
  "Secure Optimize Pdf Document",
  "Secure Optimize Document Pdf",
  "Secure Optimize Digital Pdf",
  "Secure Repair Pdf",
  "Secure Repair Pdf File",
  "Secure Repair Pdf Document",
  "Secure Repair Document Pdf",
  "Secure Repair Digital Pdf",
  "Secure Redact Pdf",
  "Secure Redact Pdf File",
  "Secure Redact Pdf Document",
  "Secure Redact Document Pdf",
  "Secure Redact Digital Pdf"
];

/**
 * Page & Tool Specific SEO Configuration Mapping
 */
export const SEO_PAGE_CONFIG = {
  home: {
    title: "CR OD Legal PDF — Free Online PDF Tools: Merge, Edit, Convert & Protect PDF Files",
    description: "One Secure Platform for Smarter, Faster PDF Management. Online View PDF, Free Edit PDF, Fast Convert PDF, Secure Merge PDF, and PDF Compression online.",
    keywords: "PDF, Online View Pdf, Free Edit Pdf, Online Convert Pdf, Free Compress Pdf, Online Merge Pdf, Fast Split Pdf, Secure Protect Pdf, PDF Management, PDF Viewer, PDF Reader",
    canonical: "https://crodlegalpdf.com/",
    heading: "One Secure Platform for Smarter, Faster PDF Management",
    breadcrumbs: [
      { name: "Home", url: "https://crodlegalpdf.com/" }
    ],
    faqs: [
      {
        question: "Is CR OD Legal PDF free to use online?",
        answer: "Yes, CR OD Legal PDF provides 100% free online PDF tools including PDF Viewer, Reader, Editor, Converter, Merger, Splitter, and Compressor with no file limits."
      },
      {
        question: "Are my uploaded PDF documents secure?",
        answer: "Absolutly. All PDF processing occurs with end-to-end encryption. Your documents remain private and secure at all times."
      }
    ]
  },
  'organize-pdf': {
    title: "Online Organize PDF — Free PDF Merger, Splitter, Page Extractor & Reorder Tool",
    description: "Free Organize PDF File. Online Merge PDF, Split PDF File, Reorder PDF Pages, Extract Digital PDF, and Rotate PDF pages fast and securely.",
    keywords: "Online Organize Pdf, Free Merge Pdf, Online Split Pdf, Reorder PDF Pages, Free Extract Pdf, Online Rotate Pdf, Fast Organize Pdf File",
    canonical: "https://crodlegalpdf.com/#organize-pdf",
    heading: "Organize PDF — Reorder, Merge, Split & Extract PDF Pages",
    breadcrumbs: [
      { name: "Home", url: "https://crodlegalpdf.com/" },
      { name: "Organize PDF", url: "https://crodlegalpdf.com/#organize-pdf" }
    ],
    faqs: [
      {
        question: "How do I merge multiple PDF files online for free?",
        answer: "Upload your PDF files into our Free Merge PDF tool, arrange the page order as desired, and click process to download a single combined PDF document."
      }
    ]
  },
  'convert-to-pdf': {
    title: "Online Convert to PDF — Free Word, Excel, JPG & PPT to PDF Converter",
    description: "Online Convert Document to PDF. Convert Word to PDF, Excel to PDF, JPG to PDF, PowerPoint to PDF, and HTML to PDF fast & free online.",
    keywords: "Online Convert Pdf, Free Convert Pdf File, Word to PDF, JPG to PDF, Excel to PDF, PPT to PDF, Fast Convert Digital Pdf",
    canonical: "https://crodlegalpdf.com/#convert-to-pdf",
    heading: "Convert to PDF — Fast & Free Document to PDF Converter",
    breadcrumbs: [
      { name: "Home", url: "https://crodlegalpdf.com/" },
      { name: "Convert to PDF", url: "https://crodlegalpdf.com/#convert-to-pdf" }
    ]
  },
  'convert-from-pdf': {
    title: "Convert PDF to Word, Excel, JPG & Text — Free Online PDF Converter",
    description: "Free Convert PDF Document. Easily convert PDF to Word, PDF to Excel, PDF to JPG, PDF to Text, and PDF to PowerPoint online with high quality.",
    keywords: "Free Convert Pdf, PDF to Word, PDF to Excel, PDF to JPG, PDF to Text, Best Convert Pdf File, Fast PDF Converter",
    canonical: "https://crodlegalpdf.com/#convert-from-pdf",
    heading: "Convert from PDF — PDF to Word, Excel, Image & Text",
    breadcrumbs: [
      { name: "Home", url: "https://crodlegalpdf.com/" },
      { name: "Convert from PDF", url: "https://crodlegalpdf.com/#convert-from-pdf" }
    ]
  },
  'pdf-security': {
    title: "Online Protect & Unlock PDF — Secure Encryption & Password Removal",
    description: "Secure Protect PDF Document. Add password encryption, remove PDF passwords, set permissions, and secure confidential PDF files online.",
    keywords: "Secure Protect Pdf, Online Protect Pdf, Free Unlock Pdf, Password Protect PDF, Remove PDF Password, Secure Digital Pdf",
    canonical: "https://crodlegalpdf.com/#pdf-security",
    heading: "PDF Security — Password Protect & Unlock PDF Files",
    breadcrumbs: [
      { name: "Home", url: "https://crodlegalpdf.com/" },
      { name: "PDF Security", url: "https://crodlegalpdf.com/#pdf-security" }
    ]
  },
  'pdf-signature': {
    title: "Online Sign PDF — Digital PDF Signer & Electronic Signature Tool",
    description: "Free Sign PDF Document. Draw your signature, upload digital signatures, and e-sign PDF contracts & legal documents online securely.",
    keywords: "Online Sign Pdf, Free Sign Pdf File, Digital PDF Signer, Electronic Signature PDF, E-Sign PDF Document, Secure Sign Digital Pdf",
    canonical: "https://crodlegalpdf.com/#pdf-signature",
    heading: "PDF Signature — E-Sign & Digitally Sign PDF Documents",
    breadcrumbs: [
      { name: "Home", url: "https://crodlegalpdf.com/" },
      { name: "PDF Signature", url: "https://crodlegalpdf.com/#pdf-signature" }
    ]
  },
  'pdf-ai-tools': {
    title: "AI Smart PDF Tools — Chat with PDF, Summarize & AI Document Search",
    description: "Smart AI PDF Reader & Analyzer. Chat with PDF documents, extract automated summaries, ask questions, and translate PDF text fast.",
    keywords: "AI PDF Reader, Chat with PDF, PDF Summarizer, Online Search Pdf, Fast Search Pdf Document, PDF AI Tools",
    canonical: "https://crodlegalpdf.com/#pdf-ai-tools",
    heading: "PDF AI Tools — Chat, Summarize & Analyze PDFs with AI",
    breadcrumbs: [
      { name: "Home", url: "https://crodlegalpdf.com/" },
      { name: "PDF AI Tools", url: "https://crodlegalpdf.com/#pdf-ai-tools" }
    ]
  },
  'compare-redaction': {
    title: "Online Compare & Redact PDF — Document Diffing & Sensitive Content Blackout",
    description: "Online Redact PDF File & Side-by-Side PDF Compare. Highlight text differences between PDF versions and permanently blackout private text.",
    keywords: "Online Redact Pdf, Free Redact Pdf File, Compare PDF Files, PDF Diff Checker, Permanently Blackout PDF, Secure Redact Digital Pdf",
    canonical: "https://crodlegalpdf.com/#compare-redaction",
    heading: "Compare & Redaction — Compare Versions & Redact Sensitive Content",
    breadcrumbs: [
      { name: "Home", url: "https://crodlegalpdf.com/" },
      { name: "Compare & Redaction", url: "https://crodlegalpdf.com/#compare-redaction" }
    ]
  }
};

/**
 * Returns dynamic SEO metadata based on active page and selected tool
 *
 * @param {string} activePage - Current active page id
 * @param {Object} [tool] - Optional selected tool object
 * @returns {Object} SEO metadata object with titles, descriptions, schema
 */
export function getSEOMetadata(activePage = 'home', tool = null) {
  if (tool) {
    const toolName = tool.name || tool.title || 'PDF Tool';
    const cleanDesc = tool.description || 'Process your PDF documents fast and securely online for free.';
    return {
      title: `${toolName} — Free ${toolName} Online | CR OD Legal PDF`,
      description: `Free ${toolName}. ${cleanDesc} Secure, fast, and easy to use online PDF management tool.`,
      keywords: `${toolName}, Free ${toolName}, Online ${toolName}, Fast ${toolName}, Secure ${toolName}, PDF Processing`,
      canonical: `https://crodlegalpdf.com/#tool-${(tool.id || toolName).toLowerCase().replace(/\s+/g, '-')}`,
      heading: toolName,
      softwareName: toolName,
      breadcrumbs: [
        { name: "Home", url: "https://crodlegalpdf.com/" },
        { name: activePage.replace(/-/g, ' ').toUpperCase(), url: `https://crodlegalpdf.com/#${activePage}` },
        { name: toolName, url: `https://crodlegalpdf.com/#tool` }
      ]
    };
  }

  const pageConfig = SEO_PAGE_CONFIG[activePage] || SEO_PAGE_CONFIG.home;
  return pageConfig;
}

/**
 * Generates JSON-LD Structured Data array for injection in document head
 *
 * @param {Object} metadata - Computed SEO metadata object
 * @returns {Array<Object>} Array of Schema.org JSON-LD objects
 */
export function generateStructuredData(metadata) {
  const schemas = [];

  // 1. Organization Schema
  schemas.push({
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "CR OD Legal PDF",
    "url": "https://crodlegalpdf.com/",
    "logo": "https://res.cloudinary.com/dlhmkbijh/image/upload/v1785473491/LegalPDFLogo_uzgtsd.png",
    "description": "One Secure Platform for Smarter, Faster PDF Management.",
    "parentOrganization": {
      "@type": "Organization",
      "name": "CR CCF"
    }
  });

  // 2. WebSite Schema with SearchAction
  schemas.push({
    "@context": "https://schema.org",
    "@type": "WebSite",
    "name": "CR OD Legal PDF Platform",
    "url": "https://crodlegalpdf.com/",
    "potentialAction": {
      "@type": "SearchAction",
      "target": "https://crodlegalpdf.com/?q={search_term_string}",
      "query-input": "required name=search_term_string"
    }
  });

  // 3. SoftwareApplication Schema
  schemas.push({
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": metadata.softwareName || metadata.heading || "CR OD Legal PDF Tools",
    "operatingSystem": "All (Web Browser)",
    "applicationCategory": "BusinessApplication",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "4.9",
      "ratingCount": "1250"
    }
  });

  // 4. BreadcrumbList Schema
  if (metadata.breadcrumbs && metadata.breadcrumbs.length > 0) {
    schemas.push({
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": metadata.breadcrumbs.map((item, idx) => ({
        "@type": "ListItem",
        "position": idx + 1,
        "name": item.name,
        "item": item.url
      }))
    });
  }

  // 5. FAQPage Schema
  if (metadata.faqs && metadata.faqs.length > 0) {
    schemas.push({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": metadata.faqs.map(faq => ({
        "@type": "Question",
        "name": faq.question,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": faq.answer
        }
      }))
    });
  }

  return schemas;
}
